version: 0.2

env:
  environment: "dev"

phases:
  install:
    commands:
      - echo building TPIP front end application
      - cd npm
      # - echo start install yarn
      # - npm install -g yarn
      # - echo Finished installing yarn
  build:
    commands:
      - echo build and copy files to S3 bucket
      - node test.js
      - echo Finished copied to s3 bucket

